[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
chess = "3.2.0"
ndarray = "0.15.6"
tch = "0.10.1"
vampirc-uci = "0.11.1"

[features]
use-external-eval = []